--drop table indexsysdb.df_tushare_usd_index_daily
CREATE TABLE indexsysdb.df_tushare_usd_index_daily(
    trade_date           String,
    USDX_index           Float64,
    pct_change           Float64,
    USDJPY_bid_open      Float64,
    USDJPY_ask_open      Float64,
    USDHKD_bid_open      Float64,
    USDHKD_ask_open      Float64,
    USDCNH_bid_open      Float64,
    USDCNH_ask_open      Float64,
    USDCHF_bid_open      Float64,
    USDCHF_ask_open      Float64,
    USDCAD_bid_open      Float64,
    USDCAD_ask_open      Float64,
    NZDUSD_bid_open      Float64,
    NZDUSD_ask_open      Float64,
    GBPUSD_bid_open      Float64,
    GBPUSD_ask_open      Float64,
    EURUSD_bid_open      Float64,
    EURUSD_ask_open      Float64,
    AUDUSD_bid_open      Float64,
    AUDUSD_ask_open      Float64,
    USDSEK_bid_open      Float64,
    USDSEK_ask_open      Float64,
    USDJPY_bid_close     Float64,
    USDJPY_ask_close     Float64,
    USDHKD_bid_close     Float64,
    USDHKD_ask_close     Float64,
    USDCNH_bid_close     Float64,
    USDCNH_ask_close     Float64,
    USDCHF_bid_close     Float64,
    USDCHF_ask_close     Float64,
    USDCAD_bid_close     Float64,
    USDCAD_ask_close     Float64,
    NZDUSD_bid_close     Float64,
    NZDUSD_ask_close     Float64,
    GBPUSD_bid_close     Float64,
    GBPUSD_ask_close     Float64,
    EURUSD_bid_close     Float64,
    EURUSD_ask_close     Float64,
    AUDUSD_bid_close     Float64,
    AUDUSD_ask_close     Float64,
    USDSEK_bid_close     Float64,
    USDSEK_ask_close     Float64
)
ENGINE=SummingMergeTree(trade_date)
order by (trade_date)
SETTINGS index_granularity = 8192

trade_date,
USDJPY_bid_open,
USDJPY_ask_open,
USDHKD_bid_open,
USDHKD_ask_open,
USDCNH_bid_open,
USDCNH_ask_open,
USDCHF_bid_open,
USDCHF_ask_open,
USDCAD_bid_open,
USDCAD_ask_open,
NZDUSD_bid_open,
NZDUSD_ask_open,
GBPUSD_bid_open,
GBPUSD_ask_open,
EURUSD_bid_open,
EURUSD_ask_open,
AUDUSD_bid_open,
AUDUSD_ask_open,
USDSEK_bid_open,
USDSEK_ask_open,
USDJPY_bid_close,
USDJPY_ask_close,
USDHKD_bid_close,
USDHKD_ask_close,
USDCNH_bid_close,
USDCNH_ask_close,
USDCHF_bid_close,
USDCHF_ask_close,
USDCAD_bid_close,
USDCAD_ask_close,
NZDUSD_bid_close,
NZDUSD_ask_close,
GBPUSD_bid_close,
GBPUSD_ask_close,
EURUSD_bid_close,
EURUSD_ask_close,
AUDUSD_bid_close,
AUDUSD_ask_close,
USDSEK_bid_close,
USDSEK_ask_close,
USDX_index
