ame: Sync from Gitee
on:
  schedule:
    - cron: '0 * * * *'  # 每小时自动同步一次
  workflow_dispatch:     # 支持手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Gitee
        run: |
          git remote add gitee https://github.com/snetlogon20/Infinity.git
          git pull gitee master --allow-unrelated-histories  # 合并 Gitee 的更新

      - name: Push to GitHub
        run: |
          git push origin master